name: appcenter_sdk_plus_example
description: "Demo app for sqlite3_async package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.24
  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  logging_appenders: ^1.3.1
  appcenter_sdk_plus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
